# Import Streamlit to create the web UI
import streamlit as st

# Import ChatGroq to connect with Groq LLM through LangChain
from langchain_groq import ChatGroq

# Import dotenv to load environment variables from .env file
from dotenv import load_dotenv

# Import os to access environment variables
import os

# Import PromptTemplate utilities from LangChain
from langchain_core.prompts import PromptTemplate, load_prompt


# Load variables from .env file (like GROQ_API_KEY)
load_dotenv()


# Display the title of the Streamlit app
st.header("Research Tool")


# Create the LLM object using Groq model
llm = ChatGroq(
    model="llama-3.1-8b-instant",     # Model name provided by Groq
    temperature=0.5,                  # Controls randomness of responses
    api_key=os.getenv("GROQ_API_KEY") # Read API key from environment variable
)


# Create a dropdown menu for selecting the research paper
paper_input = st.selectbox(
    "Select Research Paper Name",
    [
        "Attention Is All You Need",
        "BERT: Pre-training of Deep Bidirectional Transformers",
        "GPT-3: Language Models are Few-Shot Learners",
        "Diffusion Models Beat GANs on Image Synthesis"
    ]
)


# Dropdown to choose explanation style
style_input = st.selectbox(
    "Select Explanation Style",
    [
        "Beginner-Friendly",
        "Technical",
        "Code-Oriented",
        "Mathematical"
    ]
)


# Dropdown to choose explanation length
length_input = st.selectbox(
    "Select Explanation Length",
    [
        "Short (1-2 paragraphs)",
        "Medium (3-5 paragraphs)",
        "Long (detailed explanation)"
    ]
)


# Load the prompt template from the JSON file
# This template contains placeholders like {paper_input}, {style_input}, {length_input}
template = load_prompt('template.json')


# Fill the template variables with user selections
prompt = template.invoke({
    'paper_input': paper_input,
    'style_input': style_input,
    'length_input': length_input
})


# Create a button that triggers the AI summarization
if st.button('Summarize'):

    # Send the formatted prompt to the LLM
    result = llm.invoke(prompt)

    # Display the response generated by the AI
    st.write(result.content)
