"""
Simple LangChain + HuggingFace Example
--------------------------------------

This script demonstrates how to:
1. Load a HuggingFace text-generation model using LangChain.
2. Wrap it inside a ChatHuggingFace interface.
3. Send a prompt to the model.
4. Print the model's response.

Model Used:
TinyLlama/TinyLlama-1.1B-Chat-v1.0
"""

# Import required classes
from langchain_huggingface import ChatHuggingFace, HuggingFacePipeline


# Step 1: Create a HuggingFace text-generation pipeline
# ------------------------------------------------------
# from_model_id() loads a model directly from HuggingFace Hub.
# task="text-generation" specifies we want a generative model.
# pipeline_kwargs controls generation behavior.

llm = HuggingFacePipeline.from_model_id(
    model_id="TinyLlama/TinyLlama-1.1B-Chat-v1.0",  # Pretrained chat model
    task="text-generation",                        # Define task type
    pipeline_kwargs=dict(
        temperature=0.5,      # Controls randomness (lower = more deterministic)
        max_new_tokens=100    # Maximum number of tokens to generate
    )
)


# Step 2: Wrap pipeline inside ChatHuggingFace
# --------------------------------------------
# ChatHuggingFace allows conversational-style interaction
# instead of raw text generation.
model = ChatHuggingFace(llm=llm)


# Step 3: Send a prompt to the model
# -----------------------------------
# invoke() sends a single input message to the model
result = model.invoke("What is the capital of India?")


# Step 4: Print only the generated content
# ----------------------------------------
# result contains metadata + content.
# We print only the content generated by the model.
print(result.content)
